env:
  # Default
  TZ: Asia/Jakarta
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
  
  # Device
  DEVICE_CODENAME: lime
  ARCH: arm64
  CONFIG: vendor/bengal-perf_defconfig
  
  # Host
  BUILD_USER: admin
  BUILD_HOST: mrtproject
  
  # Kernel source
  KERNEL_SOURCE_URL: https://github.com/frstprjkt/valeryn_xiaomi_sm6115
  KERNEL_BRANCH_TO_CLONE: su/android13
  KERNEL_ROOTDIR: $CIRRUS_WORKING_DIR/$DEVICE_CODENAME
  
  # Toolchain
  CLANG_URL: https://github.com/MRT-project/mrt_clang/releases/download/03102025/mrt-clang-22.0.0git-03102025.tar.gz
  CLANG_BRANCH_TO_CLONE: 
  CLANG_DIR: $CIRRUS_WORKING_DIR/mrt-clang
  
  # Anykernel
  ANYKERNEL: https://github.com/frstprjkt/AnyKernel3
  
  # KSU
  KSU_ENABLE: true
  KSU_VERSION: nongki
  KSU_LKM_ENABLE: true
  KSU_OTHER_ENABLE: true
  KSU_OTHER_URL: https://github.com/SukiSU-Ultra/SukiSU-Ultra
  KSU_SKIP_PATCH: true
  COCCI_ENABLE: true
  COCCI_REPO_URL: https://github.com/dabao1955/kernel_build_action
  COCCI_SCRIPT_DIR: $CIRRUS_WORKING_DIR/cocci
  
  # KSU EXPERIMENTAL
  KSU_EXPERIMENTAL: false
  
  # BUILD TYPE
  # CC="clang" dan lain lain
  # Jika set ke false anda perlu menggunakan USE_COMPILER_EXTRA
  USE_COMPILER_DEFAULT: true
  # contoh CC="clang" AR="llvm-ar" AS="llvm-as" LD="ld.lld" NM="llvm-nm" OBJCOPY="llvm-objcopy" OBJDUMP="llvm-objdump" OBJSIZE="llvm-size" READELF="llvm-readelf" STRIP="llvm-strip" HOSTCC="clang" HOSTCXX="clang++" HOSTLD="ld.lld"
  USE_COMPILER_EXTRA:
  # (1= image.gz dan dtbo.img) (2= image.gz saja) (auto= otomatis)
  BUILD_TYPE: 1
  
  # Telegram
  TG_TOKEN: ENCRYPTED[d0276edb784fa8b652def34d72880b4851940c542e7359f5f4bf2fd580c50a2703fd253d507dbae7707b26f9c97a6062]
  TG_CHAT_ID: ENCRYPTED[4d5930d962ad8511a049ebea4a7592106705ad09d8471be9b3071ee337381d2f31c1a9a53040eeb582842361f6ec1417]

task:
  name: "Kernel Build.."
  timeout_in: 120m
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  Build_kernel_script:
    - ./build.sh
    - ./done.sh
