env:
  TZ: Asia/Jakarta

container:
  image: mhmmdfdlyas/dockerfile:k-ubuntu
  cpu: 8
  memory: 32G

cloning_task:
  name: Test
  timeout_in: 120m
  only_if: $CIRRUS_BRANCH == 'main'
  script:
    - echo "Hello word!"
