env:
  # Default
  TZ: Asia/Jakarta
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
  
  # Device
  DEVICE_CODENAME: lime
  ARCH: arm64
  CONFIG: vendor/bengal-perf_defconfig
  
  # Host
  BUILD_USER: admin
  BUILD_HOST: mrtproject
  
  # Kernel source
  KERNEL_SOURCE_URL: https://github.com/MRT-project/valeryn_xiaomi_sm6115.git
  KERNEL_BRANCH_TO_CLONE: master
  
  # Toolchain
  CLANG_URL: https://github.com/greenforce-project/greenforce_clang/releases/download/14092025/greenforce-clang-22.0.0git-14092025.tar.gz
  CLANG_BRANCH_TO_CLONE: 
  CLANG_DIR: $CIRRUS_WORKING_DIR/greenforce-clang
  
  # Anykernel
  ANYKERNEL: https://github.com/frstprjkt/AnyKernel3.git
  
  # KSU
  KSU_ENABLE: true
  KSU_VERSION: susfs-main
  KSU_LKM_ENABLE: true
  KSU_OTHER_ENABLE: true
  KSU_OTHER_URL: https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra
  
  # Telegram
  TG_TOKEN: ENCRYPTED[d0276edb784fa8b652def34d72880b4851940c542e7359f5f4bf2fd580c50a2703fd253d507dbae7707b26f9c97a6062]
  TG_CHAT_ID: ENCRYPTED[4d5930d962ad8511a049ebea4a7592106705ad09d8471be9b3071ee337381d2f31c1a9a53040eeb582842361f6ec1417]

task:
  name: "Kernel Build.."
  timeout_in: 5h
  stateful: true
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  Build_kernel_script:
    - ./build.sh
    - ./done.sh
